### PR TITLE
Fix typo in link

### PR DESCRIPTION
**Pull request by thrix**
This slipped through the review ...

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

### CODE REVIEW

**Comment by psss** [comment]
I've fixed the link, added a comment and ran `make generate`. It seems that the latest `hugo-0.58.3-1` is adding a lot of new whitespace. @rpitonak, @jpopelka, is that expected/ok?

**Comment by jpopelka** [comment]
Yes, I've noticed that too, that's why I returned to what's in F30 updates (`hugo-0.55.6-1.fc30`).
You're using `hugo` from `copr` repo?

**Comment by psss** [comment]
Yes, I'm using the copr build. I thought that one is recommended:
https://github.com/packit-service/packit.dev/#fedora
Shall we use the one from Fedora now?

**Comment by thrix** [comment]
@psss btw we now have merge rights for testing farm related updates ...

**Comment by thrix** [comment]
I do not see an issue here. Blindly mering :man_facepalming:

**Comment by thrix** [comment]
just kidding :D @psss can you use older hugo then maybe?

**Comment by jpopelka** [comment]
> Yes, I'm using the copr build. I thought that one is recommended:

That was the situation in F29 I think. Fedora updates versions should work OK now.
README update PR in #55

**Comment by psss** [comment]
Hm...

    > rpm -q hugo
    hugo-0.37.1-2.fc29.x86_64

Seems I'll have to update my Fedora ;-)

**Comment by psss** [comment]
Updated once again with `hugo-0.55.6-1.fc30.x86_64`. Now looks much better. Merging.

**Pull request merged**
